### ISSUE TITLE
Problème : fichier sans extension 

### ISSUE THREAD

**Issue by Hicha-m** [JeremyRozier/Ametice-Bot#2]
## Système

Windows

## Erreur

```
Traceback (most recent call last):
  File "e:\Users\PCH\Documents\Ametice_Bot\new\Ametice-Bot\main.py", line 17, in <module>
    asyncio.run(ametice_bot.download_all_documents())
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "e:\Users\PCH\Documents\Ametice_Bot\new\Ametice-Bot\ametice_bot.py", line 281, in download_all_documents
    await asyncio.gather(*list_tasks)
  File "e:\Users\PCH\Documents\Ametice_Bot\new\Ametice-Bot\ametice_bot.py", line 96, in _get_content_file_save
    await self._save_files(
  File "e:\Users\PCH\Documents\Ametice_Bot\new\Ametice-Bot\ametice_bot.py", line 185, in _save_files
    async with aiofiles.open(
  File "C:\Users\PCH\AppData\Roaming\Python\Python311\site-packages\aiofiles\base.py", line 78, in __aenter__
    self._obj = await self._coro
                ^^^^^^^^^^^^^^^^
  File "C:\Users\PCH\AppData\Roaming\Python\Python311\site-packages\aiofiles\threadpool\__init__.py", line 80, in _open
    f = yield from loop.run_in_executor(executor, cb)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'Fichiers_Ametice/22-23/22-23-S1-Mathematiques_S1_G._Chapuisat_pour_la_licence_MPCI/Chapitre_3_Fonctions_usuelles/correction_ex_12.php/6530081/mod_resource/content/1/ex12td3pdf'
```

## Problème

Quand le fichier a téléchargé n'a pas d'extension sa plante.

## Solution 
Dans ametice_bot.py -> fonction : _save_files

```
from urllib.parse import urlparse

    async def _save_files(
        self, binary_content, file_url, content_type, folder_path, filename
    ):
        parsed = urlparse(file_url)   # récupère les parties de l'url
        extension = os.path.splitext(parsed.path)[1][1:] # on découpe le chemin entre sa base et son extension
        if content_type == "url":
            extension = "txt"
            os.makedirs(folder_path, exist_ok=True)
            async with aiofiles.open(
                f"{folder_path}/{filename}.{extension}", mode="w"
            ) as file:
                await file.write(file_url)
        else:
            if content_type == "folder":
                extension = "zip"
            os.makedirs(folder_path, exist_ok=True)
            async with aiofiles.open(
                f"{folder_path}/{filename}.{extension}", mode="wb"
            ) as file:
                await file.write(binary_content)
```
Output :
```
ParseResult(scheme='', netloc='', path='Fichiers_Ametice/22-23/22-23-S1-Mathematiques_S1_G._Chapuisat_pour_la_licence_MPCI/Chapitre_3_Fonctions_usuelles/correction_ex_12.php/6530081/mod_resource/content/1/ex12td3pdf', params='', query='', fragment='')
('Fichiers_Ametice/22-23/22-23-S1-Mathematiques_S1_G._Chapuisat_pour_la_licence_MPCI/Chapitre_3_Fonctions_usuelles/correction_ex_12.php/6530081/mod_resource/content/1/ex12td3pdf', '')

```

urllib est déjà implémenté dans python nativement, on n'a pas besoin de l'installer, il faut juste l'importer.

**Comment by Hicha-m** [comment]
ou sinon avec le module requests c'est la même chose
```
from requests.utils import urlparse
```

**Comment by JeremyRozier** [comment]
Salut, merci pour les détails mais est ce que "correction_ex_12.php" c'est un dossier ? Si c'est le cas normalement il ne devrait y avoir aucun problème puisqu'il télécharge le zip directement.

**Comment by Hicha-m** [comment]
non, c'est un fichier pdf normalement, mais il n'a d'extension 🤷‍♂️
surement, une erreur de Charier
---
![image](https://github.com/JeremyRozier/Ametice-Bot/assets/68863445/b919310d-49ae-438f-a7b3-b22191aafa5c)

---

![image](https://github.com/JeremyRozier/Ametice-Bot/assets/68863445/ca0ca9ad-71cd-41b6-89b7-f975c307776a)

**Comment by Hicha-m** [comment]
Sur Ametice, il se présente comme ça : 

![image](https://github.com/JeremyRozier/Ametice-Bot/assets/68863445/ede906e6-57d4-4446-8f21-48d00990b2b7)

**Comment by JeremyRozier** [comment]
Je vois ok elle a oublié de mettre le ".".  J'aime bien ta solution mais son problème c'est que du coup si le prof se trompe le fichier n'aura pas d'extension. Une alternative c'est l'attribut "content_type" de la variable "page" dans la méthode "_get_content_file_save" qui retourne le MIME type du fichier. Il y a la fonction "guess_extension" du module built-in "mimetypes" qui permet ensuite d'obtenir l'extension mais pour certains MIME types comme les jupyter notebook ça ne marche pas. Donc je vais implémenter ta solution et si elle retourne une chaine vide alors j'essaierai d'avoir l'extension avec le MIME. Une solution serait d'en rajouter à la main via le module (il me semble qu'il y a une fonction pour faire ça).

**Comment by JeremyRozier** [comment]
Je pourrai

**Comment by JeremyRozier** [comment]
Je pourrai le corriger la semaine prochaine

**Comment by JeremyRozier** [comment]
C'est bon normalement j'ai corrigé le bug et j'ai corrigé d'autres problèmes aussi que j'avais pas vus. Merci beaucoup en tout cas et n'hésite pas si tu vois qu'il y a d'autres problèmes :)
